### ISSUE TITLE
Axes labeling

### ISSUE THREAD

**Issue by papersplease** [GMapeSplat/ComfyUI_ezXY#1]
Thanks for making this! XY plots iterated over arbitrary variables truly is a missing piece of the puzzle.

Is it possible to add labeling for axes? I guess the labels could be hacked on top with some custom text nodes and a bit of noodlework, but it's such a typical thing to have in a XY plot that it should probably be built-in.

**Comment by GMapeSplat** [comment]
I agree. I'm not sure how long it will take, or what it'll look like, but I am working on a labeling solution.

**Comment by GMapeSplat** [comment]
Basic label generation is in.
